target-version = "py310"

[lint]
select = ["E","F","B","I","UP","SIM","S","ANN"]

[lint.per-file-ignores]
"tests/*" = ["ANN", "S101"]
"benchmarks/*" = ["ANN", "S"]
"utils/*" = ["S"]
"*.pyi" = ["E501"]
"python/cryptopyx/stubs.py" = ["B023"]

[format]
line-ending = "lf"
quote-style = "single"
indent-style = "space"

[lint.flake8-quotes]
docstring-quotes = "double"