target-version = "py310"

[lint]
select = ["E","F","B","I","S","UP","SIM","ANN", "C90", "PL", "RUF", "PERF"]

[lint.per-file-ignores]
"tests/*" = ["ANN", "S101"]
"benchmarks/*" = ["ANN"]

[format]
line-ending = "lf"
quote-style = "single"
indent-style = "space"

[lint.flake8-quotes]
docstring-quotes = "double"