target-version = "py310"
preview = true

[lint]
select = [
    "E",      # pycodestyle errors
    "F",      # pyflakes
    "I",      # isort
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "BLE",    # flake8-blind-except (no bare except:)
    "C4",     # flake8-comprehensions
    "C90",    # mccabe complexity
    "SIM",    # flake8-simplify
    "N",      # pep8-naming
    "Q",      # flake8-quotes
    "RUF",    # Ruff-specific rules
    "ASYNC",  # flake8-async
    "S",      # flake8-bandit (security)
    "PTH",    # flake8-use-pathlib
    "ERA",    # eradicate (commented-out code)
    "PL",     # pylint
    "PERF",   # perflint (performance)
    "ANN",    # flake8-annotations
    "ARG",    # flake8-unused-arguments
    "FBT",    # flake8-boolean-trap
    "RET",    # flake8-return
    "TC",     # flake8-type-checking
]

ignore = [
    "E501" # Delegate to formatter
]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "ANN", # No annotations
    "S101" # Allow asssertations
]
"benches/*" = ["ANN"] # No annotations

[lint.mccabe]
max-complexity = 10  # Maximum cyclomatic complexity

[lint.flake8-quotes]
inline-quotes = "single"

[lint.isort]
known-first-party = ["cryptopyx"]
combine-as-imports = true
force-sort-within-sections = true

[lint.flake8-type-checking]
strict = true

[lint.pylint]
max-nested-blocks = 3  # Maximum nested block depth (PLR1702)

# Formatter
[format]
line-ending = "lf"
quote-style = "single"
indent-style = "space"