[package]
name = "_cryptopyx"
# Update pyproject version too
version = "0.1.1"
description = "Rust backend for the cryptopyx Python package"
edition = "2024"
rust-version = "1.85.0"

[lib]
name = "_cryptopyx"
crate-type = ["cdylib"]

[dependencies]

[dependencies.pyo3]
version = "0.27.0"
# "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
features = ["abi3-py310"]
